name: 'CI'
on:
  pull_request:
  push:
    branches:
    - master
    paths-ignore:
    - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Install
      run: nix-env -if .

    - run: echo TERM=ansi >> $GITHUB_ENV

    # Test basic command line usage

    # Test in an empty state
    - run: nix-desktop list
    - run: nix-desktop update

    # Install and uninstall
    - run: nix-desktop test/xdg-1
    - name: Verify the result for installing test/xdg-1
      run: 'test -e $HOME/.local/share/applications/true.desktop'

    - run: nix-desktop uninstall test/xdg-1
    - name: Verify the result for uninstalling test/xdg-1
      run: '! test -e $HOME/.local/share/applications/true.desktop'

    - run: nix-desktop install test/xdg-1

    - run: nix-desktop build test/xdg-systemd

    # Test against an environment some installations
    - run: nix-desktop list
    - run: nix-desktop update

    # Test systemd services

    # TODO: Add tests for systemd integration

    # The Ubuntu image on GitHub Actions don't seem to support
    # systemd. It produces "Failed to connect to bus: No such file or
    # directory" error.

    # - run: nix-desktop test/systemd-1
    # - name: Verify the result
    #   run: |
    #     systemctl --user --no-pager status true-1.service
    #     systemctl --user --no-pager status echo.service
    #     ! systemctl --user is-enabled true-1.service
    #     ! systemctl --user is-active true-1.service
    #     systemctl --user is-enabled echo.service
    #     systemctl --user is-active echo.service
    # - run: nix-desktop uninstall test/systemd-1
    # - name: Verify the result
    #   run: |
    #     ! systemctl --user is-enabled echo.service
    #     ! systemctl --user is-active echo.service
    #     ! systemctl --user --no-pager status true-1.service
    #     ! systemctl --user --no-pager status echo.service
